# Generated by Django 5.1.2 on 2024-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_shape_item_color_id_item_material_id_item_shape_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
