# Generated by Django 5.1.2 on 2024-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_coloritem_color_id_alter_coloritem_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
