# Generated by Django 5.1.2 on 2024-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_comment_item_id_alter_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
