# Generated by Django 5.1.2 on 2024-11-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='taste',
        ),
    ]
