# Generated by Django 5.1.2 on 2024-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
