# Generated by Django 5.1.2 on 2024-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_test_item_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='height',
        ),
        migrations.AddField(
            model_name='item',
            name='currency_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='lenght',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='measurement_unit_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
