# Generated by Django 5.1.2 on 2024-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_currency_measurementunit_rename_size_item_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lenght',
            new_name='length',
        ),
    ]
