# Generated by Django 5.1.2 on 2024-12-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
