# Generated by Django 5.1.2 on 2024-11-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.tag'),
        ),
    ]
