# Generated by Django 5.1.2 on 2024-11-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_tagitem_remove_tag_item_id_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
