# Generated by Django 5.1.2 on 2024-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_item_tag_remove_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('color_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('material_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShapeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('shape_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shape_id',
        ),
    ]
