# Generated by Django 5.1.2 on 2024-12-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_coloritem_materialitem_shapeitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
            ],
        ),
    ]
