# Generated by Django 5.1.2 on 2024-12-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_comment_date_comment_user_id_item_age_item_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MassUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MeasurementUnit',
            new_name='LengthUnit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='condition',
            new_name='functionality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='measurement_unit_id',
        ),
        migrations.AddField(
            model_name='item',
            name='condition_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='hardness_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='length_unit_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='mass_unit_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
