# Generated by Django 5.1.2 on 2024-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_condition_hardness_massunit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassUnit',
            new_name='WeightUnit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mass_unit_id',
            new_name='weight_unit_id',
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
